name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #  redis:
    #    image: valkey/valkey:8
    #    ports:
    #      - 6379:6379
    #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      CI: true
      RAILS_ENV: test
      RUBOCOP_CACHE_ROOT: tmp/rubocop
      # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      # REDIS_URL: redis://localhost:6379/0
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with: { bundler-cache: true }

      - uses: actions/cache@v4
        with:
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          # TODO: What about Ruby Version??
          key: rubocop-${{ runner.os }}-${{ hashFiles('.rubocop.yml', 'Gemfile.lock') }}-${{ github.run_id }}
          restore-keys: |
            rubocop-${{ runner.os }}-${{ hashFiles('.rubocop.yml', 'Gemfile.lock') }}-

      - run: bin/rubocop -f github
      - run: bin/rails test

